### ISSUE TITLE
package doesn't work proprerly on iOS (and Android?) because Cordova InAppBrowser doesn't support `window.close()`

### ISSUE THREAD

**Issue by jeffreywescott** [nate-strauser/meteor-accounts-saml#8]
After completing the SAML authentication process successfully, the in-app browser stays open to a page that just says "**Verified**".

FYI, this seems to have to do with two things:

1. `saml_server.js` uses `window.close()` to complete the sign-in process.
2. [Cordova InAppBrowser doesn't truly support `window.close()`](https://stackoverflow.com/questions/21085041/how-to-close-inappbrowser-itself-in-phonegap-application).

A possible workaround would be [something like this](https://stackoverflow.com/questions/15666258/phonegap-build-open-external-page-in-inappbrowser-or-childbrowser-with-no-tool/15701122#15701122).

See also: https://github.com/RocketChat/Rocket.Chat/issues/2028

**Comment by nate-strauser** [comment]
this package was modeled after the default meteor oauth behavior, which at
the time did not support single window oauth.  meteor does support this
now, so we could use the same mechanism as them.

i agree this is an issue and should be implemented.  however i will not be
able to work on this for the foreseeable future.  a PR would be welcomed if
someone else has the initiative.

**Comment by moritzmann1** [comment]
@nate-strauser Thank you for your acknowledgment. I think a lot of business users depend on this feature. What is a PR?

Is there a way to put a bounty on this defect/feature?

**Comment by nate-strauser** [comment]
PR -> pull request with the fix :)

**Comment by moritzmann1** [comment]
Nice :) Thanks you for eduction. We'll test the linked phonegap fix next week as hinted by @jeffreywescott.

**Comment by nate-strauser** [comment]
could also do something like what the core oauth package does now - set a
'loginStyle' or popup or redirect
https://github.com/meteor/meteor/blob/devel/packages/oauth/oauth_client.js#L15

handle redirect end -
https://github.com/meteor/meteor/blob/devel/packages/oauth/end_of_redirect_response.js
handle popup end -
https://github.com/meteor/meteor/blob/devel/packages/oauth/end_of_popup_response.js

there is some cordova specific popup handling here also -
https://github.com/meteor/meteor/blob/devel/packages/oauth/oauth_cordova.js

---

i'm pretty sure the core oauth package has what is needed, just have to
pull in the right bits

**Comment by rore** [comment]
Any chance for a fix for this issue? It really hurts the ability for using the mobile app of rocket.chat in a secure way in a work environment.

**Comment by nate-strauser** [comment]
i've added the ability to post a bounty -
https://www.bountysource.com/issues/30379337-package-doesn-t-work-proprerly-on-ios-and-android-because-cordova-inappbrowser-doesn-t-support-window-close?utm_campaign=plugin&utm_content=tracker%2F530713&utm_medium=issues&utm_source=github

without some other motivation (bounty or a project i'm working on using
this again) it may be quite a while before i have time to fix this

**Comment by Steibock** [comment]
What would a proper incentive/bounty be, so you could solve this soon?

**Comment by nate-strauser** [comment]
not really sure - i was thinking that it would be more driven by how much
those who want the issue resolved need/want it to be fixed

**Comment by nate-strauser** [comment]
PR submitted and merged - #10 

please try version 0.1.3 which should work on cordova
